### ISSUE TITLE
Windows XP support?

### ISSUE THREAD

**Issue by parkerlreed** [xan1242/hp2wsfix#7]
I have an XP machine setup with a lot of the games I played throughout the years.

This has everything required to play the game but doesn't start with the wsfix applied 

![image](https://user-images.githubusercontent.com/841440/79285265-094fcc80-7e8b-11ea-835a-87fbe8854317.png)

My system specs are plenty for what this needs (E8400, 3GB RAM, R7 240 2GB VRAM)

Any chances of this being supported?

**Comment by xan1242** [comment]
As per the requirements; I didn't include XP support.

Not impossible, just gotta compile this with a Visual C compiler version supporting XP and it'll be OK.
I didn't do it for simplicity's sake during development. (nor do I have a way of testing per se)

Funnily enough that crash probably wouldn't happen if I didn't use SHGetFolderPathA but I digress.

Please test with the attached .asi file and tell me if it works for you now. Of course, you'll have to install the VC redist 2015 for XP beforehand (I assume you already did seeing how far you got with that error). It is the last one made for XP anyway.

[HP2WSFix.zip](https://github.com/xan1242/hp2wsfix/files/4478499/HP2WSFix.zip)

**Comment by parkerlreed** [comment]
No change in the error. Yeah all the VC stuff is good.

**Comment by xan1242** [comment]
Well that is unfortunate, I specifically used v140_xp in VS2015 to build that one.

I'll work on it more when I get the time.

It might be just a Win32 error after all that stops it from working.

**Comment by xan1242** [comment]
Small update on the situation - this fix might not work on XP thanks to the ASI loader I use
See: https://github.com/ThirteenAG/Ultimate-ASI-Loader/issues/30

Your issue might be fixed by using an older version of the ASI loader.
In the end I might end up editing the ASI loader (since it also breaks in Linux for similar reasons)

**Comment by xan1242** [comment]
Hello, it's been a couple months, but I got around to fixing the issue of the ASI loader.
I have replaced the troublesome function call and now it works fine for the most part! 

Only limitation is that stdout doesn't work (seemingly due to Visual C++ issues) so you can't enable the console window without crashing the game...

Windows XP users, download this ASI loader and replace d3d8.dll: [DOWNLOAD LINK](https://github.com/xan1242/Ultimate-ASI-Loader/releases/download/v4.52/Ultimate-ASI-Loader-WinXP.zip)

**Comment by parkerlreed** [comment]
Just got around to trying this out. Working great!

![image](https://user-images.githubusercontent.com/841440/114971616-b36d8600-9e4a-11eb-9ff4-07eab576d936.png)
